# Generated by Django 4.2.7 on 2023-11-17 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_shippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='commune',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
