# Generated by Django 4.2.7 on 2023-11-17 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_shippingaddress_commune'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
